version: 2.1
jobs:
  build:
    working_directory: ~/myApp
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g"
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: ionic cordova build android --prod